### ISSUE TITLE
Have ellipsis in Recent Comments show the entire comment

### ISSUE THREAD

**Issue by danielbachhuber** [davemart-in/WordPress-3.8-Dashboard#1]
![image](https://f.cloud.github.com/assets/36432/1362524/966b57e6-381b-11e3-8d9f-63086a39f6dc.png)

It would be nice if the ellipsis was clickable to show the entire comment.

From http://danielbachhuber.com/2013/10/13/ux-improvement-for-the-recent-comments-dashboard-widget/

**Comment by davemart-in** [comment]
Not sure how obvious that would be for most users.  Going to mark this as won't fix for the short-term, and see if I have time to swing back to it a bit later.  Perhaps there is something else that we can link to make it more obvious?
