### ISSUE TITLE
Optimize WP_Query in Activity widget

### ISSUE THREAD

**Issue by Mamaduka** [davemart-in/WordPress-3.8-Dashboard#2]
By default `WP_Query` runs four queries - get posts, check how many post exists, get/update metadata and terms for these posts. In 'Activity' widget we only need first query.

Plus we can use `get_posts` and foreach query, `the_post` method calls `setup_postdata` which isn't really necessary here.

**Comment by Mamaduka** [comment]
@growthdesigner pushed the branch with suggested modifications.

**Comment by davemart-in** [comment]
Looks good.  I added you as a collaborator, would you mind adding this to growthdesigner/wp-dash?

**Comment by danielbachhuber** [comment]
@Mamaduka When you do, please create a pull request first. I have some feedback.

**Comment by Mamaduka** [comment]
@danielbachhuber Can you provide feedback here? Will do pull request with final code.

**Comment by davemart-in** [comment]
@Mamaduka, I'd say just get it in. We're in a bit of a time crunch to get everything wrapped up (as in this afternoon) ;-)  @danielbachhuber if you've got any feedback after he adds it, please chip in then. :-)

**Comment by danielbachhuber** [comment]
I think we should keep `WP_Query` as it is. There's no explicit advantage to using `get_posts()`.

I'd recommend just opening a PR with the arguments to skip the additional queries.

**Comment by Mamaduka** [comment]
Sounds good.

**Comment by Mamaduka** [comment]
Done, closing this one.
