### ISSUE TITLE
Syncing Git repo with WordPress.org

### ISSUE THREAD

**Issue by danielbachhuber** [davemart-in/WordPress-3.8-Dashboard#3]
Locally, I've set up WordPress trunk as a remote in my Git repo. Here's how I did it:

**1** To my .git/config file, I added:

```
[svn-remote "wporg-trunk"]
        url = http://plugins.svn.wordpress.org/dashboard/trunk
        fetch = :refs/remotes/git-svn-wporg-trunk
```

Note: If you have commit access to the repo, you'll want to use `https://USERNAME@plugins.svn.wordpress.org/dashboard/trunk` as the URL so you can push to trunk.

**2** Once the config was in place, I fetched the most recent revision `git svn fetch wporg-trunk -r 753902`

**3** You can check out the branch with `git checkout -b wporg-trunk`

**4** Once on the branch, fetch the entire history with `git svn rebase`. You'll see a bunch of output like this:

```
r785664 = 7fbee22e01919ae9d788f70b97f35483a4b2e651 (refs/remotes/wporg-trunk)
    M   quickdraft.php
    M   rightnow.php
    M   css/dash-rwd.css
    M   js/dash-rwd.js
r785996 = 4ac4b0e594c2f7741419a09b2639ab89e3268ca0 (refs/remotes/wporg-trunk)
    M   activity.php
    M   css/activity.css
    M   dashboard-override.php
    M   js/dash-rwd.js
```

**5** I did `git push -u origin wporg-trunk` to push all of these commits to a branch: https://github.com/growthdesigner/wp-dash/commits/wporg-trunk

**6** Because the original commit on master doesn't have an associated ref, I did the following up update master:

```
daniel.local ➜  wp-dash git:(wporg-trunk) git branch -d master
warning: deleting branch 'master' that has been merged to
         'refs/remotes/origin/master', but not yet merged to HEAD.
Deleted branch master (was 55d088f).
daniel.local ➜  wp-dash git:(wporg-trunk) git checkout -b master
Switched to a new branch 'master'
daniel.local ➜  wp-dash git:(master) git push -f origin master
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:growthdesigner/wp-dash.git
 + 55d088f...815bc0d master -> master (forced update)
```

`push -f` is generally considered bad form however. Going forward, it would be best to cherry-pick commits from one branch to another, or perform merges.

cc @growthdesigner

**Comment by davemart-in** [comment]
Awesome write up.  Thanks for this!
