### ISSUE TITLE
Consider offering a filter for `wp_dashboard_default_feeds()`

### ISSUE THREAD

**Issue by danielbachhuber** [davemart-in/WordPress-3.8-Dashboard#5]
It would be convenient to be able to add / remove / generally change the feeds used in the News widget. It appears you might be able to do this through the UI:

![image](https://f.cloud.github.com/assets/36432/1391618/5dd0d90a-3bff-11e3-90ba-d2e645caa47f.png)

However, I can't add or remove fields there. I think we can go down one or more of these routes:
- Offer some add / remove fields UI to the widget settings.
- Run all of the URLs through a filter.

**Comment by davemart-in** [comment]
"Offer some add / remove fields UI to the widget settings."

Tried doing that, but got pushback, as this is not an RSS widget, it's specifically meant to be a "WordPress news" widget.

"Run all of the URLs through a filter."

Seems reasonable.

**Comment by danielbachhuber** [comment]
> Tried doing that, but got pushback, as this is not an RSS widget, it's specifically meant to be a "WordPress news" widget.

I don't think that argument makes any sense if there are fields to edit the two feeds used...

**Comment by davemart-in** [comment]
They remain simply to provide a way for other translations (other than english) to be used.

**Comment by danielbachhuber** [comment]
Yeah, I think that's pretty lame and reduces the utility of the widget.

**Comment by davemart-in** [comment]
Yeah, don't know what to tell ya. ;-)
